project_id = "jaouwhckqqnaxqyfvgyq"

[functions.create-next-appointment]
verify_jwt = false

[functions.ai-assistant]
verify_jwt = false

[functions.enrich-old-transactions]
verify_jwt = true

[functions.extract-quote-data]
verify_jwt = false


